_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
colsample_bytree:
    value: 0.8194628455804146
learning_rate:
    value: 0.12096570689209232
method:
    value: random
metric:
    value:
        goal: maximize
        name: val_accuracy
min_child_samples:
    value: 58
min_child_weight:
    value: 1.0463757257205784
name:
    value: tuning lightgbm on adult
num_leaves:
    value: 87
parameters:
    value:
        colsample_bytree:
            distribution: uniform
            max: 1
            min: 0.5
        learning_rate:
            distribution: log_uniform_values
            max: 1
            min: 0.001
        min_child_samples:
            values:
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
                - 11
                - 12
                - 13
                - 14
                - 15
                - 16
                - 17
                - 18
                - 19
                - 20
                - 21
                - 22
                - 23
                - 24
                - 25
                - 26
                - 27
                - 28
                - 29
                - 30
                - 31
                - 32
                - 33
                - 34
                - 35
                - 36
                - 37
                - 38
                - 39
                - 40
                - 41
                - 42
                - 43
                - 44
                - 45
                - 46
                - 47
                - 48
                - 49
                - 50
                - 51
                - 52
                - 53
                - 54
                - 55
                - 56
                - 57
                - 58
                - 59
                - 60
                - 61
                - 62
                - 63
                - 64
                - 65
                - 66
                - 67
                - 68
                - 69
                - 70
                - 71
                - 72
                - 73
                - 74
                - 75
                - 76
                - 77
                - 78
                - 79
                - 80
                - 81
                - 82
                - 83
                - 84
                - 85
                - 86
                - 87
                - 88
                - 89
                - 90
                - 91
                - 92
                - 93
                - 94
                - 95
                - 96
                - 97
                - 98
                - 99
                - 100
        min_child_weight:
            distribution: log_uniform
            max: 0.1
            min: 1e-05
        num_leaves:
            values:
                - 10
                - 11
                - 12
                - 13
                - 14
                - 15
                - 16
                - 17
                - 18
                - 19
                - 20
                - 21
                - 22
                - 23
                - 24
                - 25
                - 26
                - 27
                - 28
                - 29
                - 30
                - 31
                - 32
                - 33
                - 34
                - 35
                - 36
                - 37
                - 38
                - 39
                - 40
                - 41
                - 42
                - 43
                - 44
                - 45
                - 46
                - 47
                - 48
                - 49
                - 50
                - 51
                - 52
                - 53
                - 54
                - 55
                - 56
                - 57
                - 58
                - 59
                - 60
                - 61
                - 62
                - 63
                - 64
                - 65
                - 66
                - 67
                - 68
                - 69
                - 70
                - 71
                - 72
                - 73
                - 74
                - 75
                - 76
                - 77
                - 78
                - 79
                - 80
                - 81
                - 82
                - 83
                - 84
                - 85
                - 86
                - 87
                - 88
                - 89
                - 90
                - 91
                - 92
                - 93
                - 94
                - 95
                - 96
                - 97
                - 98
                - 99
                - 100
        reg_lambda:
            distribution: log_uniform
            max: 1
            min: 1e-05
        subsample:
            distribution: uniform
            max: 1
            min: 0.5
reg_lambda:
    value: 1.369991544551373
subsample:
    value: 0.7227749840515779
