_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
bagging_temp:
    value: 0.25733337351608654
depth:
    value: 7.870000842020735
l2_leaf_reg:
    value: 3.0701958167377117
leaf_est_iterations:
    value: 5.569883434007886
lr:
    value: 0.04318888721346118
method:
    value: random
metric:
    value:
        goal: maximize
        name: val_acc
name:
    value: tuning catboost on adult
parameters:
    value:
        bagging_temp:
            distribution: uniform
            max: 1
            min: 0
        depth:
            distribution: uniform
            max: 10
            min: 3
        l2_leaf_reg:
            distribution: uniform
            max: 10
            min: 0.1
        leaf_est_iterations:
            distribution: uniform
            max: 10
            min: 1
        lr:
            distribution: log_uniform_values
            max: 1
            min: 0.001
