_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
method:
    value: grid
metric:
    value:
        goal: minimize
        name: val_loss
name:
    value: testing catboost on microsoft
parameters:
    value:
        seed:
            values:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
seed:
    value: 1
