_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
bagging_temperature:
    value: 0.2827606991169199
depth:
    value: 7
l2_leaf_reg:
    value: 4.0921547649185745
leaf_estimation_iterations:
    value: 1
learning_rate:
    value: 0.0026781537969379956
method:
    value: random
metric:
    value:
        goal: minimize
        name: val_loss
name:
    value: tuning catboost on regression-cat-large-0-particulate-matter-ukair-2017
parameters:
    value:
        bagging_temperature:
            distribution: uniform
            max: 1
            min: 0
        depth:
            values:
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
        l2_leaf_reg:
            distribution: uniform
            max: 10
            min: 0.1
        leaf_estimation_iterations:
            values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
        learning_rate:
            distribution: log_uniform_values
            max: 1
            min: 0.001
