# Основные параметры эксперимента
project_name: 'Kuromoto'
num_epochs: 100     # Количество эпох обучения
num_trials: 70      # Количество trials для подбора гиперпараметров
patience: 5         # Ранняя остановка после N эпох без улучшений

# тип архитектуры
arch_types: 
  - plain

model_names:
  - k_net

emb_names:
  - none

# оптимайзер 
optim_names:
  - adamw

dataset_names:
  - adult
  - gesture
  - california
  - churn
  - house 
  - diamond