# Основные параметры эксперимента
project_name: 'Optimizers Testing'
num_epochs: 100     # Количество эпох обучения
num_trials: 70      # Количество trials для подбора гиперпараметров
patience: 5         # Ранняя остановка после N эпох без улучшений

# Конфигурация моделей
model_names:
  - small_kan       # Компактная версия KAN
  - mlp             # Стандартный MLP

# Конфигурация эмбеддингов
emb_names:
  - PLE-Q           # PLE embedding

# Оптимайзер 
optim_names:
  - muon

# Оставшиеся данных для тестирования
dataset_names:
  - otto 
  - santander
  - regression-num-large-0-year
  - regression-cat-large-0-particulate-matter-ukair-2017
  - regression-cat-large-0-nyc-taxi-green-dec-2016
  - classif-cat-large-0-road-safety
  - regression-num-medium-0-medical_charges
  - classif-num-large-0-MiniBooNE

