wandb_version: 1

bagging_temperature:
  value: 0.63715674702544
depth:
  value: 9
l2_leaf_reg:
  value: 7.418693710398575
leaf_estimation_iterations:
  value: 8
learning_rate:
  value: 0.11787883020484
