num_epochs: 100
num_trials: 70
patience: 5

arch_types: 
  - plain

optim_names:
  - adamw

emb_names:
  - none
  - PLE-Q
  - periodic

model_names:
  - mlp
  - small_kan

dataset_names:
  - adult
  - california
  - churn
  - house
  - diamond
  
  - higgs-small
  - black-friday
  - fb-comments