num_epochs: 100
num_trials: 70
patience: 5

arch_types: 
  - plain

optim_names:
  - adamw

model_names:
  - small_kan
  - mlp
  - fast_kan

dataset_names:
  - adult
  - churn
  - higgs-small
  - santander
  - classif-cat-large-0-road-safety
  - classif-num-large-0-MiniBooNE

