num_epochs: 100
num_trials: 70
patience: 5

model_names:
  - small_kan
  - mlp

emb_names:
  - PLE-Q

dataset_names:
  - adult
  - gesture
  - california
  - churn
  - house
  - diamond
  
  - higgs-small
  - black-friday
  - fb-comments