num_epochs: 100
num_trials: 70
patience: 5

model_names:
  - small_kan
  - mlp

emb_names:
  - PLE-Q

optim_names:
  - muon
  - ademamix
  - mars

dataset_names:
  - adult
  - california
  - churn
  - house
  - diamond
  
  - higgs-small
  - black-friday
  - fb-comments