# Основные параметры эксперимента
num_epochs: 100     # Количество эпох обучения
num_trials: 70      # Количество trials для подбора гиперпараметров
patience: 5         # Ранняя остановка после N эпох без улучшений

# Конфигурация моделей
model_names:
  - small_kan       # Компактная версия KAN
  - mlp             # Стандартный MLP

# Конфигурация эмбеддингов
emb_names:
  - PLE-Q           # PLE embedding

# Наборы данных для тестирования
dataset_names:
  # Стандартные датасеты
  - adult           # Adult Census Income
  - gesture         # Gesture Phase Segmentation
  - california      # California Housing
  - churn           # Customer Churn Prediction
  - house           # House Price Prediction
  - diamond         # Diamond Prices
  
  # Крупные датасеты
  - higgs-small     # Упрощенная версия Higgs Boson
  - black-friday    # Black Friday Purchases
  - fb-comments     # Facebook Comment Volume