# Основные параметры эксперимента
num_epochs: 100     # Количество эпох обучения
num_trials: 70      # Количество trials для подбора гиперпараметров
patience: 5         # Ранняя остановка после N эпох без улучшений

# тип архитектуры
arch_types: 
  - tabm-mini

# оптимайзер 
optim_names:
  - adamw