num_epochs: 100
num_trials: 70
patience: 5

arch_types: 
  - tabm-mini
 
optim_names:
  - adamw

model_names:
  - small_kan
  - mlp

dataset_names:
  - adult
  - california
  - churn
  - house
  - diamond
  
  - higgs-small
  - black-friday
  - fb-comments