_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
colsample_bytree:
    value: 0.7696966121234243
gamma:
    value: 30.43494680964854
lambda:
    value: 3951.1267321766823
learning_rate:
    value: 0.005966936819477214
max_depth:
    value: 9
method:
    value: random
metric:
    value:
        goal: maximize
        name: val_acc
min_child:
    value: 4.608567209962277e+09
name:
    value: tuning xgboost on adult
parameters:
    value:
        colsample_bytree:
            distribution: uniform
            max: 1
            min: 0.5
        gamma:
            distribution: uniform
            max: 100
            min: 0.001
        lambda:
            distribution: log_uniform
            max: 10
            min: 0.1
        learning_rate:
            distribution: log_uniform_values
            max: 1
            min: 0.001
        max_depth:
            values:
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
        min_child:
            distribution: log_uniform
            max: 100
            min: 0.0001
        subsample:
            distribution: uniform
            max: 1
            min: 0.5
subsample:
    value: 0.7313961800936005
